version: '3'
services:
  
  nosql-db: 
    image: mongo
    ports:
      - "27017:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/products/node_modules
  shopping:
    build:
      context: ./shopping
      dockerfile: Dockerfile
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/shopping/node_modules
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/customer/node_modules
  nginx-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - products
      - customer
      - shopping
    ports:
      - "80:80"

